### ISSUE TITLE
Add more macros for assertions in SkTest

### ISSUE THREAD

**Issue by kagurakanon** [kkshinkai/skjvm#7]
Now we only have `require(actual == expected, "...")`. We probably need these:

```cpp
require_true(condition, "...")
require_false(condition, "...")
require_eq(left, right, "...")
require_ne(left, right, "...")
```

These should not be difficult to implement, for example:

```cpp
#define require_true(condition, ...) require((condition), __VA_ARGS__)
#define require_false(condition, ...) require(!(condition), __VA_ARGS__)
```

**Comment by kagurakanon** [comment]
If it's okay with you, I'll open a PR.

**Comment by kkshinkai** [comment]
> If it's okay with you, I'll open a PR.

Thanks!

Two more questions.

1.  `assert_true`, `assert_false`, `assert_equal`, and `assert_neq` maybe better names, `require` is a legacy naming from Catch2. By the way, I don't like abbreviations, so I think `equal` / `not_equal` may be better name than `eq` / `ne`.
2.  Directly reusing require macros is not a good idea. Error messages can become confusing.

    ```cpp
    assert_equal(1, 2)

    error: test failed at /xxx/xxx/xxx.cpp:xx
    test group:   xxxxxxxx
    expression:   require( !((1) == (2)) )
    //            ^^^^^^^  ^^^^^^^^^^^^^ I've never written this expression before.
    //            |
    //            I used `assert_equal`, why does it show this?
    ```

    Maybe we need to rewrite the `sktest::Assertion` class.

**Comment by kkshinkai** [comment]
Of course, we need to keep the `require` macro to ensure backward compatibility

**Comment by kagurakanon** [comment]
Got it.
