### ISSUE TITLE
Remove the `-nostdinc++` compile option

### ISSUE THREAD

**Issue by kagurakanon** [kkshinkai/skjvm#8]
- This option brings no real benefits, e.g., it does not reduce the size of the executable, it does not increase the compilation speed, etc.
- Some `std` functions can only be implemented by hacking the compiler like initializer list and type traits. `std` is a part of the language, not just a library.

**Comment by kkshinkai** [comment]
Agree, remove `add_compile_options(-nostdinc++)` as you wish.
